stages:
  - build
  - test

# defining the jobs inside the stages
build: # job 1
    stage: build # belongs to the build stage
    script # what are we going to do
        - echo "building"
        - mkdir build
        - touch build/info.txt
test: # job 2
    stage: test # belongs to the test stage
    script:
        - echo "testing"
        - test -f "build/info.txt"